--------------------------------------------------------
--  파일이 생성됨 - 토요일-4월-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARD" 
   (	"BID" NUMBER(4,0), 
	"BTITLE" VARCHAR2(50 BYTE), 
	"BCONTENT" VARCHAR2(300 BYTE), 
	"BNAME" VARCHAR2(10 BYTE), 
	"BDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"BHIT" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.BOARD
SET DEFINE OFF;
Insert into SCOTT.BOARD (BID,BTITLE,BCONTENT,BNAME,BDATE,BHIT) values (26,'안녕하세요','김건입니다','강정훈 ',to_timestamp('18/04/12 05:25:41.000000000','RR/MM/DD HH24:MI:SSXFF'),0);
Insert into SCOTT.BOARD (BID,BTITLE,BCONTENT,BNAME,BDATE,BHIT) values (28,'안녕하세요','김건입니다','강정훈 ',to_timestamp('18/04/12 05:25:43.000000000','RR/MM/DD HH24:MI:SSXFF'),0);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" ADD PRIMARY KEY ("BID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BHIT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BCONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BTITLE" NOT NULL ENABLE);
