--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARD" 
   (	"BID" NUMBER(4,0), 
	"BTITLE" VARCHAR2(50 BYTE), 
	"BCONTENT" VARCHAR2(300 BYTE), 
	"BNAME" VARCHAR2(20 BYTE), 
	"BDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"BHIT" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.BOARD
SET DEFINE OFF;
Insert into SCOTT.BOARD (BID,BTITLE,BCONTENT,BNAME,BDATE,BHIT) values (20,'안녕','김건입니다.','김건',to_timestamp('18/04/16 06:15:52.000000000','RR/MM/DD HH24:MI:SSXFF'),0);
Insert into SCOTT.BOARD (BID,BTITLE,BCONTENT,BNAME,BDATE,BHIT) values (12,'바이','바이','김동엽',to_timestamp('18/04/15 23:48:28.000000000','RR/MM/DD HH24:MI:SSXFF'),1);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" ADD PRIMARY KEY ("BID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BHIT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BCONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BTITLE" NOT NULL ENABLE);
